/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nuveira_nuveiraapp_NativeBridge */

#ifndef _Included_com_nuveira_nuveiraapp_NativeBridge
#define _Included_com_nuveira_nuveiraapp_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nuveira_nuveiraapp_NativeBridge
 * Method:    setOilData
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_setOilData
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_nuveira_nuveiraapp_NativeBridge
 * Method:    getPricePerGramTL
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_getPricePerGramTL
  (JNIEnv *, jobject);

/*
 * Class:     com_nuveira_nuveiraapp_NativeBridge
 * Method:    get50MLPrice
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_get50MLPrice
  (JNIEnv *, jobject);

/*
 * Class:     com_nuveira_nuveiraapp_NativeBridge
 * Method:    roundToNearest100
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_roundToNearest100
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_nuveira_nuveiraapp_NativeBridge
 * Method:    getUsdRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_getUsdRate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
