/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_nuveira_nuveiraapp_NativeBridge
#define _Included_com_nuveira_nuveiraapp_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_setOilData
  (JNIEnv *, jobject, jfloat, jfloat);

JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_get50MLPrice
  (JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_getUsdRate
  (JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_getLiveRateFromC
  (JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_getPricePerGramTL
  (JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_roundToNearest100
  (JNIEnv *, jobject, jfloat);

JNIEXPORT void JNICALL Java_com_nuveira_nuveiraapp_NativeBridge_setExchangeRate
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif